package grouptwo.quizexam.model;

import java.io.Serializable;

/**
 * Answer generated by hbm2java
 */
public class Answer implements Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Integer question;
	private String answer;

	public Answer() {
	}

	public Answer(int id, Integer question, String answer) {
		this.id = id;
		this.question = question;
		this.answer = answer;
	}
	public Answer(Integer question, String answer) {
		this.question = question;
		this.answer = answer;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getQuestions() {
		return this.question;
	}

	public void setQuestions(Integer question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
