package grouptwo.quizexam.model;

/**
 * Answer generated by hbm2java
 */
public class Answer  {

	private int id;
	private Question question;
	private String answer;

	public Answer() {
	}

	public Answer(int id, Question question, String answer) {
		this.id = id;
		this.question = question;
		this.answer = answer;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Question getQuestions() {
		return this.question;
	}

	public void setQuestions(Question question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
