// default package
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

/**
 * DetailexamsId generated by hbm2java
 */
public class DetailexamsId implements java.io.Serializable {

	private int exam;
	private int question;

	public DetailexamsId() {
	}

	public DetailexamsId(int exam, int question) {
		this.exam = exam;
		this.question = question;
	}

	public int getExam() {
		return this.exam;
	}

	public void setExam(int exam) {
		this.exam = exam;
	}

	public int getQuestion() {
		return this.question;
	}

	public void setQuestion(int question) {
		this.question = question;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailexamsId))
			return false;
		DetailexamsId castOther = (DetailexamsId) other;

		return (this.getExam() == castOther.getExam()) && (this.getQuestion() == castOther.getQuestion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExam();
		result = 37 * result + this.getQuestion();
		return result;
	}

}
