// default package
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

/**
 * Detailexams generated by hbm2java
 */
public class Detailexams implements java.io.Serializable {

	private DetailexamsId id;
	private Exams exams;
	private Questions questions;

	public Detailexams() {
	}

	public Detailexams(DetailexamsId id, Exams exams, Questions questions) {
		this.id = id;
		this.exams = exams;
		this.questions = questions;
	}

	public DetailexamsId getId() {
		return this.id;
	}

	public void setId(DetailexamsId id) {
		this.id = id;
	}

	public Exams getExams() {
		return this.exams;
	}

	public void setExams(Exams exams) {
		this.exams = exams;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

}
