package grouptwo.quizexam.Model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profilemanager generated by hbm2java
 */
public class Profilemanager implements java.io.Serializable {

	private String usersUserName;
	private Users users;
	private String name;
	private Date dateOfBirth;
	private String gender;
	private String email;
	private String phoneNumber;
	private String image;
	private byte showProfile;
	private Set classeses = new HashSet(0);
	private Set questionses = new HashSet(0);
	private Set examses = new HashSet(0);

	public Profilemanager() {
	}

	public Profilemanager(Users users, String name, Date dateOfBirth, String gender, String email, String phoneNumber,
			byte showProfile) {
		this.users = users;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.showProfile = showProfile;
	}

	public Profilemanager(Users users, String name, Date dateOfBirth, String gender, String email, String phoneNumber,
			String image, byte showProfile, Set classeses, Set questionses, Set examses) {
		this.users = users;
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.image = image;
		this.showProfile = showProfile;
		this.classeses = classeses;
		this.questionses = questionses;
		this.examses = examses;
	}

	public String getUsersUserName() {
		return this.usersUserName;
	}

	public void setUsersUserName(String usersUserName) {
		this.usersUserName = usersUserName;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public byte getShowProfile() {
		return this.showProfile;
	}

	public void setShowProfile(byte showProfile) {
		this.showProfile = showProfile;
	}

	public Set getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set classeses) {
		this.classeses = classeses;
	}

	public Set getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set questionses) {
		this.questionses = questionses;
	}

	public Set getExamses() {
		return this.examses;
	}

	public void setExamses(Set examses) {
		this.examses = examses;
	}

}
