package grouptwo.quizexam.model;
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

/**
 * Questioncategories generated by hbm2java
 */
public class Questioncategorie {

	private int id;
	private String categoryName;


	public Questioncategorie() {
	}

	public Questioncategorie(int id, String categoryName) {
		this.id = id;
		this.categoryName = categoryName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	





}
