// default package
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Questioncategories generated by hbm2java
 */
public class Questioncategories implements java.io.Serializable {

	private int id;
	private String categoryName;
	private Set questionses = new HashSet(0);

	public Questioncategories() {
	}

	public Questioncategories(int id, String categoryName) {
		this.id = id;
		this.categoryName = categoryName;
	}

	public Questioncategories(int id, String categoryName, Set questionses) {
		this.id = id;
		this.categoryName = categoryName;
		this.questionses = questionses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Set getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set questionses) {
		this.questionses = questionses;
	}

}
