package grouptwo.quizexam.Model;
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer id;
	private Answer answer;
	private Profilemanager profilemanager;
	private Questioncategories questioncategories;
	private String question;
	private String image;
	private String level;
	private Set answers = new HashSet(0);
	private Set detailexamses = new HashSet(0);

	public Questions() {
	}

	public Questions(Answer answer, Profilemanager profilemanager, Questioncategories questioncategories,
			String question, String level) {
		this.answer = answer;
		this.profilemanager = profilemanager;
		this.questioncategories = questioncategories;
		this.question = question;
		this.level = level;
	}

	public Questions(Answer answer, Profilemanager profilemanager, Questioncategories questioncategories,
			String question, String image, String level, Set answers, Set detailexamses) {
		this.answer = answer;
		this.profilemanager = profilemanager;
		this.questioncategories = questioncategories;
		this.question = question;
		this.image = image;
		this.level = level;
		this.answers = answers;
		this.detailexamses = detailexamses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Answer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Answer answer) {
		this.answer = answer;
	}

	public Profilemanager getProfilemanager() {
		return this.profilemanager;
	}

	public void setProfilemanager(Profilemanager profilemanager) {
		this.profilemanager = profilemanager;
	}

	public Questioncategories getQuestioncategories() {
		return this.questioncategories;
	}

	public void setQuestioncategories(Questioncategories questioncategories) {
		this.questioncategories = questioncategories;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

	public Set getDetailexamses() {
		return this.detailexamses;
	}

	public void setDetailexamses(Set detailexamses) {
		this.detailexamses = detailexamses;
	}

}
