package grouptwo.quizexam.Model;

/**
 * Resulttests generated by hbm2java
 */
public class Resulttests implements java.io.Serializable {

	private int id;
	private Exams exams;
	private Profilestudent profilestudent;
	private int score;

	public Resulttests() {
	}

	public Resulttests(int id, Exams exams, Profilestudent profilestudent, int score) {
		this.id = id;
		this.exams = exams;
		this.profilestudent = profilestudent;
		this.score = score;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Exams getExams() {
		return this.exams;
	}

	public void setExams(Exams exams) {
		this.exams = exams;
	}

	public Profilestudent getProfilestudent() {
		return this.profilestudent;
	}

	public void setProfilestudent(Profilestudent profilestudent) {
		this.profilestudent = profilestudent;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

}
