package grouptwo.quizexam.Model;
// Generated Nov 17, 2018, 5:02:38 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Roleusers generated by hbm2java
 */
public class Roleusers implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Set userses = new HashSet(0);

	public Roleusers() {
	}

	public Roleusers(String roleName) {
		this.roleName = roleName;
	}

	public Roleusers(String roleName, Set userses) {
		this.roleName = roleName;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
