package grouptwo.quizexam.model;

import java.util.List;

import grouptwo.quizexam.service.RoleuserService;

/**
 * Users generated by hbm2java
 */
public class User {

	private Integer userId;
	private String userName;
	private Integer roleuser;
	private Roleuser roleObject;
	private List<String> roleName;
	private String email;
	private String password;
	private boolean activate;
	public User() {
	}

	public User(Integer userId, String userName, String email, String password, Integer roleuser, boolean activate) {
		this.userId = userId;
		this.userName = userName;
		this.roleuser = roleuser;
		this.email = email;
		this.password = password;
		this.activate = activate;
		this.roleObject=RoleuserService.getRoleUserById(roleuser);
	}

	public User(String userName, String email, String password, Integer roleuser, boolean activate) {
		this.userName = userName;
		this.roleuser = roleuser;
		this.email = email;
		this.password = password;
		this.activate = activate;
		this.roleObject=RoleuserService.getRoleUserById(roleuser);
	}


	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getRoleuser() {
		return this.roleuser;
	}

	public void setRoleusers(Integer roleuser) {
		this.roleuser = roleuser;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean getActivate() {
		return this.activate;
	}

	public void setActivate(boolean activate) {
		this.activate = activate;
	}
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Roleuser getRoleObject() {
		return roleObject;
	}

	public void setRoleObject(Roleuser roleObject) {
		this.roleObject = roleObject;
	}

	public List<String> getRoleName() {
		return roleName;
	}

	public void setRoleName(List<String> roleName) {
		this.roleName = roleName;
	}


}
